### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by kdykeman** [jordansissel/ruby-grok#24]
Can you please add a license declaration?  Without declaring an explicit license for this work, it's unclear what my rights and obligations are when using the code.

**Comment by ph** [comment]
Good point, I am pretty sure it should be license with an Apache 2 License @jordansissel am I right?

**Comment by harspras** [comment]
@jordansissel Any update regarding what kind of license will be applicable for this?

**Comment by harspras** [comment]
@jordansissel @ph  any update on this?

**Comment by jordansissel** [comment]
AGPL3? Apache 2? BSD?

My original grok implementation, I think, was New BSD licensed, as is the successor `grok` (uses libpcre which is GPL+LGPL).

I'm OK with Apache 2 or AGPL3 (preference for AGPL3, to be honest)

**Comment by harspras** [comment]
@jordansissel Thank you for your response. And sorry for pestering you. ^_^;
To be honest, if it's Apache 2 then it's much easier to use the code or the gem distribution. But it's definitely your call though.

**Comment by harspras** [comment]
@jordansissel Any updates?

**Comment by elmekiesisrael** [comment]
Hi, 

Can you please add a license to your code? I am unable to use it without some license. 

As @harspras mentiond, Apache2.0 license will be preferable, but of curse, this is your call.

Thank you very much!!!

**Comment by ph** [comment]
@jordansissel I am ok with Apache 2? Not sure about the difference with AGPL3 :)

**Comment by elmekiesisrael** [comment]
https://stackoverflow.com/questions/2982364/how-does-apache-2-0-license-differ-from-gpl

Is it possible to add an Apache2.0 license to this project?

**Comment by webmat** [comment]
@jordansissel This can be closed.

Good news everyone! As of [0.11.5](https://rubygems.org/gems/jls-grok/versions/0.11.5), this gem is officially Apache 2 :-)
